### PR TITLE
Implement write feature

### PR DESCRIPTION
**Pull request by jagedn**
This PR implement the write functionality of a parquet file

the method requires a path and a `Record` class to let the plugin know about the internal structure of the file to create

### CODE REVIEW

**Comment by jagedn** [comment]
@pditommaso @bentsherman can you take a look to this pr? Would be great to have v0.0.1 of this plugin published

**Comment by bentsherman** [comment]
It looks fine to me, as long as you have tests that are passing. Do you not have the ability to merge?

Also, out of curiosity, does this library work only with record types or can it work with any class?

**Comment by jagedn** [comment]
> It looks fine to me, as long as you have tests that are passing. Do you not have the ability to merge?
> 

No, I can't merge:(

> Also, out of curiosity, does this library work only with record types or can it work with any class?

Exactly,  it works only with records. To read you can use Map (so it will read all fields) but a record is required to write

**Comment by bentsherman** [comment]
@pditommaso I'm fine with giving Jorge merge permissions on this repo, what do you think

**Comment by jagedn** [comment]
hi folks
sorry to be missing for a while, if you don't mind I would like to continue with this project and work on it so we can publish soon a first release version

**Comment by pditommaso** [comment]
Jorge, think you are an admin of this project

**Comment by jagedn** [comment]
due some issues couldnt accept the invitation link and it expired

**Pull request closed without merging**
